apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  # - csidriver.yaml
  # - node-daemonset.yaml
  # - node-serviceaccount.yaml
  # - controller-deployment.yaml
  # - controller-serviceaccount.yaml
  # - clusterrole-csi-node.yaml
  # - clusterrolebinding-csi-node.yaml

  - ./rbac/iam-scope/iam-policies.yaml
  - ./rbac/iam-scope/iam-roles.yaml
  - ./rbac/k8s-scope/cluster-roles.yaml
  - ./rbac/k8s-scope/role-bindings.yaml
  - ./rbac/k8s-scope/service-accounts.yaml
  - ./app/csidriver.yaml
  - ./app/node-daemonset.yaml
  - ./app/controller-deployment.yaml