apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: infrastructure/base/addons
  serviceAccountName: kustomize-controller
  path: ./kyverno
  prune: true
  timeout: 5m
