apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  # - calico.yaml
  - kyverno.yaml
  - efs-csi.yaml
  # - vpc-cni.yaml
  # - eks-charts-helm.yaml
  # - nginx-ingress-controller.yaml
  # - prometheus-source.yaml
  # - flagger.yaml