---
# Source: aws-fsx-csi-driver/templates/controller-serviceaccount.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fsx-csi-external-provisioner-binding
  labels:
    app.kubernetes.io/name: aws-fsx-csi-driver
subjects:
  - kind: ServiceAccount
    name: fsx-csi-controller-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: fsx-csi-external-provisioner-role
  apiGroup: rbac.authorization.k8s.io
---
# Source: aws-fsx-csi-driver/templates/controller-serviceaccount.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fsx-csi-resizer-binding
  labels:
    app.kubernetes.io/name: aws-fsx-csi-driver
subjects:
  - kind: ServiceAccount
    name: fsx-csi-controller-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: fsx-external-resizer-role
  apiGroup: rbac.authorization.k8s.io

---
  # Source: aws-fsx-csi-driver/templates/clusterrolebinding-csi-node.yaml
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: fsx-csi-node-getter-binding
    labels:
      app.kubernetes.io/name: aws-fsx-csi-driver
  subjects:
    - kind: ServiceAccount
      name: fsx-csi-node-sa
      namespace: default
  roleRef:
    kind: ClusterRole
    name: fsx-csi-node-role
    apiGroup: rbac.authorization.k8s.io