---
# Source: aws-fsx-csi-driver/templates/controller-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fsx-csi-controller-sa
  labels:
    app.kubernetes.io/name: aws-fsx-csi-driver
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::526718405617:role/eks-irsa-fsxlustrecsidriver-role
---
# Source: aws-fsx-csi-driver/templates/node-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fsx-csi-node-sa
  labels:
    app.kubernetes.io/name: aws-fsx-csi-driver