apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: default
spec:
  interval: 5m
  targetNamespace: kyverno
  chart:
    spec:
      chart: kyverno
      version: '1.2.1'
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      interval: 1m
  values:
    createSelfSignedCert: true
    fullnameOverride: kyverno
    namespace: kyverno